  //Example instantiation for system 'vga_ref_2C35'
  vga_ref_2C35 vga_ref_2C35_inst
    (
      .B_from_the_vga_controller       (B_from_the_vga_controller),
      .G_from_the_vga_controller       (G_from_the_vga_controller),
      .M1_from_the_vga_controller      (M1_from_the_vga_controller),
      .M2_from_the_vga_controller      (M2_from_the_vga_controller),
      .R_from_the_vga_controller       (R_from_the_vga_controller),
      .SRAM_ADDR_from_the_sram         (SRAM_ADDR_from_the_sram),
      .SRAM_CE_N_from_the_sram         (SRAM_CE_N_from_the_sram),
      .SRAM_DQ_to_and_from_the_sram    (SRAM_DQ_to_and_from_the_sram),
      .SRAM_LB_N_from_the_sram         (SRAM_LB_N_from_the_sram),
      .SRAM_OE_N_from_the_sram         (SRAM_OE_N_from_the_sram),
      .SRAM_UB_N_from_the_sram         (SRAM_UB_N_from_the_sram),
      .SRAM_WE_N_from_the_sram         (SRAM_WE_N_from_the_sram),
      .blank_n_from_the_vga_controller (blank_n_from_the_vga_controller),
      .clk_in                          (clk_in),
      .hsync_from_the_vga_controller   (hsync_from_the_vga_controller),
      .reset_n                         (reset_n),
      .sdram_clk                       (sdram_clk),
      .select_n_to_the_ext_flash       (select_n_to_the_ext_flash),
      .sync_n_from_the_vga_controller  (sync_n_from_the_vga_controller),
      .sync_t_from_the_vga_controller  (sync_t_from_the_vga_controller),
      .sys_clk                         (sys_clk),
      .tri_state_bridge_address        (tri_state_bridge_address),
      .tri_state_bridge_data           (tri_state_bridge_data),
      .tri_state_bridge_readn          (tri_state_bridge_readn),
      .vga_clk                         (vga_clk),
      .vga_clk_to_the_vga_controller   (vga_clk_to_the_vga_controller),
      .vsync_from_the_vga_controller   (vsync_from_the_vga_controller),
      .write_n_to_the_ext_flash        (write_n_to_the_ext_flash),
      .zs_addr_from_the_sdram          (zs_addr_from_the_sdram),
      .zs_ba_from_the_sdram            (zs_ba_from_the_sdram),
      .zs_cas_n_from_the_sdram         (zs_cas_n_from_the_sdram),
      .zs_cke_from_the_sdram           (zs_cke_from_the_sdram),
      .zs_cs_n_from_the_sdram          (zs_cs_n_from_the_sdram),
      .zs_dq_to_and_from_the_sdram     (zs_dq_to_and_from_the_sdram),
      .zs_dqm_from_the_sdram           (zs_dqm_from_the_sdram),
      .zs_ras_n_from_the_sdram         (zs_ras_n_from_the_sdram),
      .zs_we_n_from_the_sdram          (zs_we_n_from_the_sdram)
    );

